# Generated by Django 2.2 on 2019-04-12 09:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0005_auto_20190411_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, unique=True), size=None),
        ),
    ]
